# Data Exploration and Cleaning

In [ ]:
import pandas as pd

In [12]:
file_path = '/Users/yujinlee/Downloads/leaderboard.test.data.20130318_20.txt'
df = pd.read_csv(file_path, sep='\t', header=None)

# Group by the creative ID and count the occurrences of each unique value
frequency = df.groupby(18).size().reset_index(name='Frequency').tail()

# Rename the columns
frequency.columns = ['18th Column Value', 'Frequency']

# Display the group-by attribute and its frequency
print(frequency)

                   18th Column Value  Frequency
28  ebbd8035bba9def2a673154ee2486e7a     143024
29  f206493d1a82b7d977075b20b7afd5f4     443271
30  f7e7cdcd8b8ed4d6682d78c5b8c4446c     132392
31  fa6d6688558d5e338490fe7c5984c822        183
32  fb82c5506a7745b09752a995de85c708      13680


In [22]:
print(df.shape)
print(df[0].nunique())

(2594386, 24)
2592453


In [23]:
df.head(5000).groupby(18)[[13,14]].nunique()

13  14
18                                      
02adb1d6bc7233c0735dbefe9bb85ecd   1   1
0abb99569043fe758ba6a51714782ced   1   1
28425676c2469651ba969a88529eeec8   1   1
2b79ac0b6110d91fbb1160dcce775b6d   1   1
36391fa23e0928a93cd51ea8af344b82   1   1
3a0cf3767556609a1f4329c9f52e387e   1   1
475d63a4a414634cb5b95dc826a6258f   1   1
4937b21d6f6c38560823917e19403fa7   1   1
51fd94f6624989b7cecbc307f00f97f7   1   1
5a57c1d215ab05643a1bce7e402c45ec   1   1
5aca4c5f29e59e425c7ea657fdaac91e   1   1
63aa53fb1f727ebe3d56c69db5097574   1   1
873a7eb504df9f4e2f16b66f61b24044   1   1
8f86b069dbb8898e2beca5ec3030e147   1   1
9c23f8ef21ec419a5bdc37c5bae78450   1   1
b0d9e0a4ece6145ba15b42ae519cadb6   1   1
c2253060edbeefa754ac5a6418d35362   1   1
ca165a0bf41928c7ec45df6c2745cf6e   1   1
cfe9f50e234d74317336d04dfa3494a3   1   1
d683498a1e531a0f3621d2f7b0a9dcf7   1   1
d76818d93532855570f2af04f52b1ef1   1   1
f206493d1a82b7d977075b20b7afd5f4   1   1
f7e7cdcd8b8ed4d6682d78c5b8c4446c   1   1
fb82c5506a7745b09752a995de85c708   1   1

In [16]:
df.head(2)

0                  1   2   \
0  b006d2236cd8786f8269e3bd60dd795f  20130318000100765   1   
1  72f80b647a1ee74dd131c00f5dbb0174  20130318000100802   1   

                                 3   \
0  c43a65560b3c8adc7cfe24ef38e82398   
1  d09e956039c402a4c36513920c06bc84   

                                                  4             5   6    7   \
0  Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...  60.190.192.*  94  100   
1  Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1...   175.170.0.*  40   42   

   8                     9   ...  14  15 16  17  \
0   2    eF1gtp57dNFrw9Kbu-  ...  60   0  0  13   
1   2  3F9-GK9SGqs8jdpz5SqW  ...  90   2  0   5   

                                 18   19  20  \
0  28425676c2469651ba969a88529eeec8  300  13   
1  5aca4c5f29e59e425c7ea657fdaac91e  300  25   

                                 21 22  23  
0  9f4e2f16b6873a7eb504df6f61b24044  0   0  
1  df6f61b2409f4e2f16b6873a7eb50444  0   0  

[2 rows x 24 columns]

In [14]:
print(df.iloc[1])

0                      72f80b647a1ee74dd131c00f5dbb0174
1                                     20130318000100802
2                                                     1
3                      d09e956039c402a4c36513920c06bc84
4     Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1...
5                                           175.170.0.*
6                                                    40
7                                                    42
8                                                     2
9                                  3F9-GK9SGqs8jdpz5SqW
10                     ba5f614bb0a90cd04add4e87ac056f4b
11                                                  NaN
12                                           3847964765
13                                                  728
14                                                   90
15                                                    2
16                                                    0
17                                              

In [11]:
df_new = df.head()
df_new.to_csv('/Users/yujinlee/Downloads/sample_testing.txt', sep='\t', header=None, index=False)

In [4]:
file_path2 = '/Users/yujinlee/Downloads/leaderboard.test.data.20131021_28.txt'
df2 = pd.read_csv(file_path2, sep='\t', header=None)
print(df2.shape)
print(df2[0].nunique())


/var/folders/yw/mp5v5fdx1_n4b01714b8bdl80000gn/T/ipykernel_78735/3635662187.py:2: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv(file_path2, sep='\t', header=None)


(1579086, 26)
1577079


In [26]:
file_path3 = '/Users/yujinlee/Downloads/leaderboard.test.data.20130613_15.txt'
df3 = pd.read_csv(file_path3, sep='\t', header=None)
print(df3.shape)
print(df3[0].nunique())

(2521630, 26)
2516352


In [5]:
print(df2.iloc[1])

0                      ce5a2b810ada0cad122508b4a9d1e2fd
1                                     20131022000104929
2                                                     1
3                                           DABNgoCoaME
4     Mozilla/4.0 (compatible; MSIE 7.0; Windows NT ...
5                                          210.21.228.*
6                                                   216
7                                                   219
8                                                   2.0
9                      72187db00c907f6304a240c763a6e70a
10                     aec76e88cbd89cda04697eb2bcd65235
11                                                  NaN
12                                           2552203011
13                                                  300
14                                                  250
15                                            FirstView
16                                                   Na
17                                              

### Combine Three Separate Test Datasets Into One

One of the three test datasets is missing two columns. We convert values in the missing columns to 0 and concat all datasets. The missing values will not be used in the prediction.

In [3]:
import pandas as pd

file_path = '/Users/yujinlee/Downloads/leaderboard.test.data.20130318_20.txt'
df = pd.read_csv(file_path, sep='\t', header=None)

In [22]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
print(df.tail(100)[[4]])

                                                         4
2594286  Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...
2594287  Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...
2594288  Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...
2594289  Mozilla/4.0 (compatible; MSIE 8.0; Windows NT ...
2594290  Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...
2594291  Mozilla/4.0 (compatible; MSIE 7.0; Windows NT ...
2594292  Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...
2594293  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...
2594294  Mozilla/5.0 (Windows NT 5.1; rv:19.0) Gecko/20...
2594295  Mozilla/4.0 (compatible; MSIE 9.0; Windows NT ...
2594296  Mozilla/4.0 (compatible; MSIE 8.0; Windows NT ...
2594297  Mozilla/4.0 (compatible; MSIE 8.0; Windows NT ...
2594298  Mozilla/4.0 (compatible; MSIE 8.0; Windows NT ...
2594299  Mozilla/4.0 (compatible; MSIE 8.0; Windows NT ...
2594300  Mozilla/5.0 (Windows NT 6.1; WOW64; rv:19.0) G...
2594301  Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1.

In [24]:
df.dtypes

0      object
1       int64
2       int64
3      object
4      object
5      object
6       int64
7       int64
8       int64
9      object
10     object
11    float64
12     object
13      int64
14      int64
15      int64
16      int64
17      int64
18     object
19      int64
20      int64
21     object
22      int64
23      int64
dtype: object

In [3]:
file_path = '/Users/yujinlee/Downloads/'
df1 = pd.read_csv(file_path + 'leaderboard.test.data.20130318_20.txt', sep='\t', header=None)
print(df1.shape)

(2594386, 24)


In [5]:
df1.head()

0                  1   2   \
0  b006d2236cd8786f8269e3bd60dd795f  20130318000100765   1   
1  72f80b647a1ee74dd131c00f5dbb0174  20130318000100802   1   
2  6f8cee7aecd741b28ad303e9bb9cf1eb  20130318000100827   1   
3  58fcbfa5f1c6381a207456157301d9d3  20130318000100837   1   
4  f6c97f428a534bc515a52e1eab9b53cf  20130318000100840   1   

                                 3   \
0  c43a65560b3c8adc7cfe24ef38e82398   
1  d09e956039c402a4c36513920c06bc84   
2  519a2259e67cc42c5d422a16a28b5b0a   
3  46f2497b959b6e5f331032c5a8985281   
4  6fa09a1916b9eb75010f756e4fb276fb   

                                                  4              5   6    7   \
0  Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...   60.190.192.*  94  100   
1  Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1...    175.170.0.*  40   42   
2  Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.1...  123.186.178.*  40   45   
3  Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...  180.125.218.*  80   85   
4  Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.7...  117.148.123.*   0    0   

   8                        9   ...   14  15 16  17  \
0   2       eF1gtp57dNFrw9Kbu-  ...   60   0  0  13   
1   2     3F9-GK9SGqs8jdpz5SqW  ...   90   2  0   5   
2   1  5F97t5E0BTK7XhNrUMpENpn  ...  600   2  1   0   
3   2          trqRTvprB9b7gsz  ...  250   2  0   5   
4   2     trqRTuNygI5ogg5A5SqW  ...  250   2  0   5   

                                 18   19  20  \
0  28425676c2469651ba969a88529eeec8  300  13   
1  5aca4c5f29e59e425c7ea657fdaac91e  300  25   
2  36391fa23e0928a93cd51ea8af344b82  300  13   
3  f206493d1a82b7d977075b20b7afd5f4  300  24   
4  f206493d1a82b7d977075b20b7afd5f4  300  57   

                                 21 22  23  
0  9f4e2f16b6873a7eb504df6f61b24044  0   0  
1  df6f61b2409f4e2f16b6873a7eb50444  0   0  
2  df6f61b2409f4e2f16b6873a7eb50444  0   0  
3  df6f61b2409f4e2f16b6873a7eb50444  0   0  
4  df6f61b2409f4e2f16b6873a7eb50444  0   0  

[5 rows x 24 columns]

In [11]:
df1[15].unique() # ad slot visibility


array([  0,   2,   1, 255])

In [12]:
df1[16].unique() # ad slot visibility


array([0, 1])

In [4]:
df2 = pd.read_csv(file_path + 'leaderboard.test.data.20130613_15.txt', sep='\t', header=None)
print(df2.shape)

(2521630, 26)


In [6]:
df2.head()

0                  1   2                3   \
0  82aed71bea7358c9a5be868deae30be0  20130613000101373   1  Vh5KZAnrPQTPJIC   
1  77c5c149c234a0de420eefe9b6e16517  20130613000101391   1  Vh1HP3FpOUx6kgL   
2  a45fe947ffb7a52f452308bb50b4a572  20130613000101428   1  Vh5zPuc9DvT2lGk   
3    184d6f9a71c3c53336cff407e5b7ae  20130613000101438   1  Vh5KZAnrPoddkMf   
4  11415ce7ca9c7e1950b41bf3468fb288  20130613000101456   1  VhdiPkNq3QNvwQL   

                                                  4              5    6    7   \
0  Mozilla/5.0 (Windows NT 6.1) AppleWebKit/535.1...    60.187.41.*   94  100   
1  Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1...     221.0.14.*  146  147   
2  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   180.173.50.*   79   79   
3  Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...  175.148.162.*   40   51   
4  Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.1...  111.179.205.*  183  193   

   8                         9   ... 16  17                                18  \
0   1      trqRTuToMTNUjM9r5rMi  ...  1   0  cc9b344e950b4f8c2b96537174a343b7   
1   1           trqRTu1YP5scFsf  ...  1   0  fa8f0532dd5144b5fa748459e8d90b49   
2   2   3K9RquSEQqk7gh5mumpWUvj  ...  0   5  7184c9560e68e977187e67e45a4f3198   
3   1  eF1gtK9cXqT7jOMoarjWvpdh  ...  5   0  44966cc8da1ed40c95d59e863c8c75f0   
4   1        trqRTummPvas1m58uG  ...  1   0  911b2d84826786018761e8c0b0a3a60c   

    19   20                                21    22  \
0  227   29  d29e59bf0f7f8243858b8183f14d4412  3358   
1  227   20  0f951a030abdaedd733ee8d114ce2944  3427   
2  238   63  0f951a030abdaedd733ee8d114ce2944  3427   
3  300  293  361e128affece850342293213691a043  3386   
4  227  120  d29e59bf0f7f8243858b8183f14d4412  3358   

                                                  23 24  25  
0                                              10063  0   0  
1          13403,10006,10063,13866,10126,10117,10110  0   0  
2  13042,10052,10075,10006,10031,10063,13800,1013...  0   0  
3                                        13866,10111  0   0  
4    13042,10031,10063,10006,10075,10126,10116,10110  0   0  

[5 rows x 26 columns]

In [13]:
df2[15].unique() # ad slot visibility


array([  0,   2,   1, 255])

In [17]:
df2[16].unique() # ad slot format


array([1, 0, 5])

In [15]:
df3 = pd.read_csv(file_path + 'leaderboard.test.data.20131021_28.txt', sep='\t', header=None)
print(df3.shape)

/var/folders/yw/mp5v5fdx1_n4b01714b8bdl80000gn/T/ipykernel_10224/1227880409.py:1: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df3 = pd.read_csv(file_path + 'leaderboard.test.data.20131021_28.txt', sep='\t', header=None)


(1579086, 26)


In [16]:
df3[15].unique() # ad slot visibility


array(['OtherView', 'FirstView', 'Na', 'ThirdView', 'SecondView',
       'FourthView', 'FifthView'], dtype=object)

In [18]:
df3[16].unique() # ad slot format


array(['Na'], dtype=object)

In [5]:
print(df1.iloc[:5, [20, 21]])

   20                                21
0  13  9f4e2f16b6873a7eb504df6f61b24044
1  25  df6f61b2409f4e2f16b6873a7eb50444
2  13  df6f61b2409f4e2f16b6873a7eb50444
3  24  df6f61b2409f4e2f16b6873a7eb50444
4  57  df6f61b2409f4e2f16b6873a7eb50444


In [6]:
print(df1.iloc[:5, [22, 23]])

   22  23
0   0   0
1   0   0
2   0   0
3   0   0
4   0   0


In [18]:
# insert 0s in the 23rd and 24th position (col index 22 and 23)
df1.insert(22, '22_new', 0)
df1.head()

0                  1  2  \
0  b006d2236cd8786f8269e3bd60dd795f  20130318000100765  1   
1  72f80b647a1ee74dd131c00f5dbb0174  20130318000100802  1   
2  6f8cee7aecd741b28ad303e9bb9cf1eb  20130318000100827  1   
3  58fcbfa5f1c6381a207456157301d9d3  20130318000100837  1   
4  f6c97f428a534bc515a52e1eab9b53cf  20130318000100840  1   

                                  3  \
0  c43a65560b3c8adc7cfe24ef38e82398   
1  d09e956039c402a4c36513920c06bc84   
2  519a2259e67cc42c5d422a16a28b5b0a   
3  46f2497b959b6e5f331032c5a8985281   
4  6fa09a1916b9eb75010f756e4fb276fb   

                                                   4              5   6    7  \
0  Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...   60.190.192.*  94  100   
1  Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1...    175.170.0.*  40   42   
2  Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.1...  123.186.178.*  40   45   
3  Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...  180.125.218.*  80   85   
4  Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.7...  117.148.123.*   0    0   

   8                        9  ... 15  16  17  \
0  2       eF1gtp57dNFrw9Kbu-  ...  0   0  13   
1  2     3F9-GK9SGqs8jdpz5SqW  ...  2   0   5   
2  1  5F97t5E0BTK7XhNrUMpENpn  ...  2   1   0   
3  2          trqRTvprB9b7gsz  ...  2   0   5   
4  2     trqRTuNygI5ogg5A5SqW  ...  2   0   5   

                                 18   19  20  \
0  28425676c2469651ba969a88529eeec8  300  13   
1  5aca4c5f29e59e425c7ea657fdaac91e  300  25   
2  36391fa23e0928a93cd51ea8af344b82  300  13   
3  f206493d1a82b7d977075b20b7afd5f4  300  24   
4  f206493d1a82b7d977075b20b7afd5f4  300  57   

                                 21  22_new 22  23  
0  9f4e2f16b6873a7eb504df6f61b24044       0  0   0  
1  df6f61b2409f4e2f16b6873a7eb50444       0  0   0  
2  df6f61b2409f4e2f16b6873a7eb50444       0  0   0  
3  df6f61b2409f4e2f16b6873a7eb50444       0  0   0  
4  df6f61b2409f4e2f16b6873a7eb50444       0  0   0  

[5 rows x 25 columns]

In [19]:
df1.insert(23, '23_new', 0)
df1.head()

0                  1  2  \
0  b006d2236cd8786f8269e3bd60dd795f  20130318000100765  1   
1  72f80b647a1ee74dd131c00f5dbb0174  20130318000100802  1   
2  6f8cee7aecd741b28ad303e9bb9cf1eb  20130318000100827  1   
3  58fcbfa5f1c6381a207456157301d9d3  20130318000100837  1   
4  f6c97f428a534bc515a52e1eab9b53cf  20130318000100840  1   

                                  3  \
0  c43a65560b3c8adc7cfe24ef38e82398   
1  d09e956039c402a4c36513920c06bc84   
2  519a2259e67cc42c5d422a16a28b5b0a   
3  46f2497b959b6e5f331032c5a8985281   
4  6fa09a1916b9eb75010f756e4fb276fb   

                                                   4              5   6    7  \
0  Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...   60.190.192.*  94  100   
1  Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1...    175.170.0.*  40   42   
2  Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.1...  123.186.178.*  40   45   
3  Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...  180.125.218.*  80   85   
4  Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.7...  117.148.123.*   0    0   

   8                        9  ... 16  17                                18  \
0  2       eF1gtp57dNFrw9Kbu-  ...  0  13  28425676c2469651ba969a88529eeec8   
1  2     3F9-GK9SGqs8jdpz5SqW  ...  0   5  5aca4c5f29e59e425c7ea657fdaac91e   
2  1  5F97t5E0BTK7XhNrUMpENpn  ...  1   0  36391fa23e0928a93cd51ea8af344b82   
3  2          trqRTvprB9b7gsz  ...  0   5  f206493d1a82b7d977075b20b7afd5f4   
4  2     trqRTuNygI5ogg5A5SqW  ...  0   5  f206493d1a82b7d977075b20b7afd5f4   

    19  20                                21  22_new  23_new 22  23  
0  300  13  9f4e2f16b6873a7eb504df6f61b24044       0       0  0   0  
1  300  25  df6f61b2409f4e2f16b6873a7eb50444       0       0  0   0  
2  300  13  df6f61b2409f4e2f16b6873a7eb50444       0       0  0   0  
3  300  24  df6f61b2409f4e2f16b6873a7eb50444       0       0  0   0  
4  300  57  df6f61b2409f4e2f16b6873a7eb50444       0       0  0   0  

[5 rows x 26 columns]

In [20]:
df1 = df1.rename(columns={22:24, 23:25, '22_new': 22, '23_new': 23})
print(df1.shape)

(2594386, 26)


In [21]:
combined_df = pd.concat([df2, df3], axis=0, ignore_index=True)
combined_df.head()

0                  1   2   \
0  b006d2236cd8786f8269e3bd60dd795f  20130318000100765   1   
1  72f80b647a1ee74dd131c00f5dbb0174  20130318000100802   1   
2  6f8cee7aecd741b28ad303e9bb9cf1eb  20130318000100827   1   
3  58fcbfa5f1c6381a207456157301d9d3  20130318000100837   1   
4  f6c97f428a534bc515a52e1eab9b53cf  20130318000100840   1   

                                 3   \
0  c43a65560b3c8adc7cfe24ef38e82398   
1  d09e956039c402a4c36513920c06bc84   
2  519a2259e67cc42c5d422a16a28b5b0a   
3  46f2497b959b6e5f331032c5a8985281   
4  6fa09a1916b9eb75010f756e4fb276fb   

                                                  4              5   6    7   \
0  Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...   60.190.192.*  94  100   
1  Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1...    175.170.0.*  40   42   
2  Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.1...  123.186.178.*  40   45   
3  Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...  180.125.218.*  80   85   
4  Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.7...  117.148.123.*   0    0   

    8                        9   ... 16  17                                18  \
0  2.0       eF1gtp57dNFrw9Kbu-  ...  0  13  28425676c2469651ba969a88529eeec8   
1  2.0     3F9-GK9SGqs8jdpz5SqW  ...  0   5  5aca4c5f29e59e425c7ea657fdaac91e   
2  1.0  5F97t5E0BTK7XhNrUMpENpn  ...  1   0  36391fa23e0928a93cd51ea8af344b82   
3  2.0          trqRTvprB9b7gsz  ...  0   5  f206493d1a82b7d977075b20b7afd5f4   
4  2.0     trqRTuNygI5ogg5A5SqW  ...  0   5  f206493d1a82b7d977075b20b7afd5f4   

    19  20                                21 22  23 24  25  
0  300  13  9f4e2f16b6873a7eb504df6f61b24044  0   0  0   0  
1  300  25  df6f61b2409f4e2f16b6873a7eb50444  0   0  0   0  
2  300  13  df6f61b2409f4e2f16b6873a7eb50444  0   0  0   0  
3  300  24  df6f61b2409f4e2f16b6873a7eb50444  0   0  0   0  
4  300  57  df6f61b2409f4e2f16b6873a7eb50444  0   0  0   0  

[5 rows x 26 columns]

In [24]:
combined_df.to_csv('/Users/yujinlee/downloads/combined_training.txt', sep='\t', index=False)

In [23]:
print(combined_df.shape)

(6695102, 26)


The combined data has 6.7 million rows.

### Create weekday and hour columns from the datetime column

In [7]:
# create new time columns
import pandas as pd

# Replace 'your_dataset.txt' with the path to your actual dataset file
file_path = '/Users/yujinlee/Downloads/combined_training.txt'

# Read the dataset into a DataFrame
df = pd.read_csv(file_path, sep='\t')

/var/folders/yw/mp5v5fdx1_n4b01714b8bdl80000gn/T/ipykernel_54924/839936535.py:8: DtypeWarning: Columns (12,15,16,18,21,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, sep='\t')


In [8]:
df.head()

0                  1  2  \
0  b006d2236cd8786f8269e3bd60dd795f  20130318000100765  1   
1  72f80b647a1ee74dd131c00f5dbb0174  20130318000100802  1   
2  6f8cee7aecd741b28ad303e9bb9cf1eb  20130318000100827  1   
3  58fcbfa5f1c6381a207456157301d9d3  20130318000100837  1   
4  f6c97f428a534bc515a52e1eab9b53cf  20130318000100840  1   

                                  3  \
0  c43a65560b3c8adc7cfe24ef38e82398   
1  d09e956039c402a4c36513920c06bc84   
2  519a2259e67cc42c5d422a16a28b5b0a   
3  46f2497b959b6e5f331032c5a8985281   
4  6fa09a1916b9eb75010f756e4fb276fb   

                                                   4              5   6    7  \
0  Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...   60.190.192.*  94  100   
1  Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1...    175.170.0.*  40   42   
2  Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.1...  123.186.178.*  40   45   
3  Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...  180.125.218.*  80   85   
4  Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.7...  117.148.123.*   0    0   

     8                        9  ... 16  17                                18  \
0  2.0       eF1gtp57dNFrw9Kbu-  ...  0  13  28425676c2469651ba969a88529eeec8   
1  2.0     3F9-GK9SGqs8jdpz5SqW  ...  0   5  5aca4c5f29e59e425c7ea657fdaac91e   
2  1.0  5F97t5E0BTK7XhNrUMpENpn  ...  1   0  36391fa23e0928a93cd51ea8af344b82   
3  2.0          trqRTvprB9b7gsz  ...  0   5  f206493d1a82b7d977075b20b7afd5f4   
4  2.0     trqRTuNygI5ogg5A5SqW  ...  0   5  f206493d1a82b7d977075b20b7afd5f4   

    19  20                                21 22  23 24  25  
0  300  13  9f4e2f16b6873a7eb504df6f61b24044  0   0  0   0  
1  300  25  df6f61b2409f4e2f16b6873a7eb50444  0   0  0   0  
2  300  13  df6f61b2409f4e2f16b6873a7eb50444  0   0  0   0  
3  300  24  df6f61b2409f4e2f16b6873a7eb50444  0   0  0   0  
4  300  57  df6f61b2409f4e2f16b6873a7eb50444  0   0  0   0  

[5 rows x 26 columns]

In [10]:
df['1'].head()

0    20130318000100765
1    20130318000100802
2    20130318000100827
3    20130318000100837
4    20130318000100840
Name: 1, dtype: int64

In [11]:
df['datetime'] = pd.to_datetime(df['1'], format='%Y%m%d%H%M%S%f')

# Extract weekday and hour
df['weekday'] = df['datetime'].dt.day_name()  # This will give the name of the day
df['hour'] = df['datetime'].dt.hour  # This will give the hour

# Now df has the original timestamp, the parsed datetime, the weekday, and the hour
df.head()

0                  1  2  \
0  b006d2236cd8786f8269e3bd60dd795f  20130318000100765  1   
1  72f80b647a1ee74dd131c00f5dbb0174  20130318000100802  1   
2  6f8cee7aecd741b28ad303e9bb9cf1eb  20130318000100827  1   
3  58fcbfa5f1c6381a207456157301d9d3  20130318000100837  1   
4  f6c97f428a534bc515a52e1eab9b53cf  20130318000100840  1   

                                  3  \
0  c43a65560b3c8adc7cfe24ef38e82398   
1  d09e956039c402a4c36513920c06bc84   
2  519a2259e67cc42c5d422a16a28b5b0a   
3  46f2497b959b6e5f331032c5a8985281   
4  6fa09a1916b9eb75010f756e4fb276fb   

                                                   4              5   6    7  \
0  Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...   60.190.192.*  94  100   
1  Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1...    175.170.0.*  40   42   
2  Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.1...  123.186.178.*  40   45   
3  Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...  180.125.218.*  80   85   
4  Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.7...  117.148.123.*   0    0   

     8                        9  ...   19  20  \
0  2.0       eF1gtp57dNFrw9Kbu-  ...  300  13   
1  2.0     3F9-GK9SGqs8jdpz5SqW  ...  300  25   
2  1.0  5F97t5E0BTK7XhNrUMpENpn  ...  300  13   
3  2.0          trqRTvprB9b7gsz  ...  300  24   
4  2.0     trqRTuNygI5ogg5A5SqW  ...  300  57   

                                 21  22  23 24 25                datetime  \
0  9f4e2f16b6873a7eb504df6f61b24044   0   0  0  0 2013-03-18 00:01:00.765   
1  df6f61b2409f4e2f16b6873a7eb50444   0   0  0  0 2013-03-18 00:01:00.802   
2  df6f61b2409f4e2f16b6873a7eb50444   0   0  0  0 2013-03-18 00:01:00.827   
3  df6f61b2409f4e2f16b6873a7eb50444   0   0  0  0 2013-03-18 00:01:00.837   
4  df6f61b2409f4e2f16b6873a7eb50444   0   0  0  0 2013-03-18 00:01:00.840   

  weekday  hour  
0  Monday     0  
1  Monday     0  
2  Monday     0  
3  Monday     0  
4  Monday     0  

[5 rows x 29 columns]

In [13]:
df.to_csv('/Users/yujinlee/downloads/combined_training.txt', sep='\t', index=False)

### Rename Columns

In [ ]:
file_path = '/Users/yujinlee/Downloads/'
df = pd.read_csv(file_path + 'combined_training.txt', sep='\t')
print(df.shape)

/var/folders/yw/mp5v5fdx1_n4b01714b8bdl80000gn/T/ipykernel_67419/3878672483.py:2: DtypeWarning: Columns (12,15,16,18,21,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path + 'combined_training.txt', sep='\t')


(6695102, 29)


In [ ]:
df.head()

0                  1  2  \
0  b006d2236cd8786f8269e3bd60dd795f  20130318000100765  1   
1  72f80b647a1ee74dd131c00f5dbb0174  20130318000100802  1   
2  6f8cee7aecd741b28ad303e9bb9cf1eb  20130318000100827  1   
3  58fcbfa5f1c6381a207456157301d9d3  20130318000100837  1   
4  f6c97f428a534bc515a52e1eab9b53cf  20130318000100840  1   

                                  3  \
0  c43a65560b3c8adc7cfe24ef38e82398   
1  d09e956039c402a4c36513920c06bc84   
2  519a2259e67cc42c5d422a16a28b5b0a   
3  46f2497b959b6e5f331032c5a8985281   
4  6fa09a1916b9eb75010f756e4fb276fb   

                                                   4              5   6    7  \
0  Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...   60.190.192.*  94  100   
1  Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1...    175.170.0.*  40   42   
2  Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.1...  123.186.178.*  40   45   
3  Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...  180.125.218.*  80   85   
4  Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.7...  117.148.123.*   0    0   

     8                        9  ...   19  20  \
0  2.0       eF1gtp57dNFrw9Kbu-  ...  300  13   
1  2.0     3F9-GK9SGqs8jdpz5SqW  ...  300  25   
2  1.0  5F97t5E0BTK7XhNrUMpENpn  ...  300  13   
3  2.0          trqRTvprB9b7gsz  ...  300  24   
4  2.0     trqRTuNygI5ogg5A5SqW  ...  300  57   

                                 21  22  23 24 25                 datetime  \
0  9f4e2f16b6873a7eb504df6f61b24044   0   0  0  0  2013-03-18 00:01:00.765   
1  df6f61b2409f4e2f16b6873a7eb50444   0   0  0  0  2013-03-18 00:01:00.802   
2  df6f61b2409f4e2f16b6873a7eb50444   0   0  0  0  2013-03-18 00:01:00.827   
3  df6f61b2409f4e2f16b6873a7eb50444   0   0  0  0  2013-03-18 00:01:00.837   
4  df6f61b2409f4e2f16b6873a7eb50444   0   0  0  0  2013-03-18 00:01:00.840   

  weekday  hour  
0  Monday     0  
1  Monday     0  
2  Monday     0  
3  Monday     0  
4  Monday     0  

[5 rows x 29 columns]

In [ ]:
df.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24',
       '25', 'datetime', 'weekday', 'hour'],
      dtype='object')

In [ ]:
df = df.rename(columns={'0':'bidID', '1':"timestamp", '2':"logtype", '3':"iPinYouID", '4':"userAgent",
                        '5':"IP", '6':"region", '7':"city", '8':"adExchange", '9':"domain", '10': "URL",
                        '11': "URLID", '12': "adSlotID", '13':"width", '14':"height", '15':"visibility",
                        '16': "format", '17': "floorPrice", '18': "creativeID", '19': "biddingPrice",
                        '20': "payingPrice", '21': "keyPageURL", '22': "advertiserID", '23': "userTags",
                        '24': "numClick", '25': "conversion"})
df.head()

bidID          timestamp  logtype  \
0  b006d2236cd8786f8269e3bd60dd795f  20130318000100765        1   
1  72f80b647a1ee74dd131c00f5dbb0174  20130318000100802        1   
2  6f8cee7aecd741b28ad303e9bb9cf1eb  20130318000100827        1   
3  58fcbfa5f1c6381a207456157301d9d3  20130318000100837        1   
4  f6c97f428a534bc515a52e1eab9b53cf  20130318000100840        1   

                          iPinYouID  \
0  c43a65560b3c8adc7cfe24ef38e82398   
1  d09e956039c402a4c36513920c06bc84   
2  519a2259e67cc42c5d422a16a28b5b0a   
3  46f2497b959b6e5f331032c5a8985281   
4  6fa09a1916b9eb75010f756e4fb276fb   

                                           userAgent             IP  region  \
0  Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...   60.190.192.*      94   
1  Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1...    175.170.0.*      40   
2  Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.1...  123.186.178.*      40   
3  Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...  180.125.218.*      80   
4  Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.7...  117.148.123.*       0   

   city  adExchange                   domain  ... biddingPrice  payingPrice  \
0   100         2.0       eF1gtp57dNFrw9Kbu-  ...          300           13   
1    42         2.0     3F9-GK9SGqs8jdpz5SqW  ...          300           25   
2    45         1.0  5F97t5E0BTK7XhNrUMpENpn  ...          300           13   
3    85         2.0          trqRTvprB9b7gsz  ...          300           24   
4     0         2.0     trqRTuNygI5ogg5A5SqW  ...          300           57   

                         keyPageURL  advertiserID  userTags numClick  \
0  9f4e2f16b6873a7eb504df6f61b24044             0         0        0   
1  df6f61b2409f4e2f16b6873a7eb50444             0         0        0   
2  df6f61b2409f4e2f16b6873a7eb50444             0         0        0   
3  df6f61b2409f4e2f16b6873a7eb50444             0         0        0   
4  df6f61b2409f4e2f16b6873a7eb50444             0         0        0   

  conversion                 datetime weekday  hour  
0          0  2013-03-18 00:01:00.765  Monday     0  
1          0  2013-03-18 00:01:00.802  Monday     0  
2          0  2013-03-18 00:01:00.827  Monday     0  
3          0  2013-03-18 00:01:00.837  Monday     0  
4          0  2013-03-18 00:01:00.840  Monday     0  

[5 rows x 29 columns]

### Convert Number of Clicks to Binary
#### Whether or not an impression was clicked matters more than the number of clicks done by the same user

In [ ]:
import numpy as np
# convert number of clicks to binary
df['numClick'] = np.where(df['numClick'] > 0, 1, 0)

In [ ]:
df.dtypes

bidID            object
timestamp         int64
logtype           int64
iPinYouID        object
userAgent        object
IP               object
region            int64
city              int64
adExchange      float64
domain           object
URL              object
URLID           float64
adSlotID         object
width             int64
height            int64
visibility       object
format           object
floorPrice        int64
creativeID       object
biddingPrice      int64
payingPrice       int64
keyPageURL       object
advertiserID      int64
userTags         object
numClick          int64
conversion        int64
datetime         object
weekday          object
hour              int64
dtype: object

In [ ]:
numeric_column = pd.to_numeric(df['visibility'], errors='coerce')

### Excluding Ineligible Columns for ML Models

In [ ]:
df['visibility'][numeric_column.isnull()]

5116016    OtherView
5116017    FirstView
5116018    OtherView
5116019           Na
5116020    OtherView
             ...    
6695097           Na
6695098    OtherView
6695099           Na
6695100    OtherView
6695101           Na
Name: visibility, Length: 1579086, dtype: object

In [ ]:
df['visibility'].unique()

array([0, 2, 1, 255, '0', '2', 'OtherView', 'FirstView', 'Na',
       'ThirdView', 'SecondView', 'FourthView', 'FifthView'], dtype=object)

In [ ]:
df[["region", "city", "adExchange", "width", "height", "floorPrice",'numClick']].describe()

region          city    adExchange         width        height  \
count  6.695102e+06  6.695102e+06  6.539039e+06  6.695102e+06  6.695102e+06   
mean   1.471080e+02  1.513030e+02  2.065239e+00  5.344556e+02  1.972643e+02   
std    1.019561e+02  1.029728e+02  8.636732e-01  3.112182e+02  1.298185e+02   
min    0.000000e+00  0.000000e+00  1.000000e+00  1.200000e+02  5.000000e+01   
25%    7.900000e+01  7.900000e+01  1.000000e+00  3.000000e+02  9.000000e+01   
50%    1.460000e+02  1.480000e+02  2.000000e+00  3.360000e+02  2.500000e+02   
75%    2.160000e+02  2.220000e+02  3.000000e+00  9.500000e+02  2.500000e+02   
max    3.950000e+02  3.990000e+02  4.000000e+00  1.000000e+03  6.000000e+02   

         floorPrice      numClick  
count  6.695102e+06  6.695102e+06  
mean   2.141370e+01  7.378528e-04  
std    3.377694e+01  2.715343e-02  
min    0.000000e+00  0.000000e+00  
25%    0.000000e+00  0.000000e+00  
50%    5.000000e+00  0.000000e+00  
75%    3.100000e+01  0.000000e+00  
max    2.990000e+02  1.000000e+00

In [ ]:
df[["region", "city", "adExchange", "width", "height", "floorPrice"]].isnull().sum()

region             0
city               0
adExchange    156063
width              0
height             0
floorPrice         0
dtype: int64

In [ ]:
df['adExchange'].unique()

array([ 2.,  1.,  3.,  4., nan])

In [ ]:
df['adExchange'].fillna(0, inplace=True)
df['adExchange'].unique()

array([2., 1., 3., 4., 0.])

In [ ]:
# df to csv
df.to_csv('/Users/yujinlee/downloads/combined_training_before_normalize.txt', sep='\t', index=False)

In [18]:
df.tail()
df.tail().to_csv('/Users/yujinlee/downloads/sample_combined_training_before_normalize.txt', sep='\t', index=False)

In [17]:
df.iloc[:,28]

0           0
1           0
2           0
3           0
4           0
           ..
6695097    16
6695098    11
6695099    11
6695100    12
6695101    17
Name: hour, Length: 6695102, dtype: int64

In [9]:
df.columns.get_loc('bidID')

0

In [6]:
df.columns.get_loc('hour')

28

In [7]:
df.columns.get_loc('numClick')

24

In [8]:
df.columns.get_loc('payingPrice')

20